nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.4.cjs
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
# httpProxy: "http://hogehoge.proxy:8080"
# httpsProxy: "http://hogehoge.proxy:8080"
